package openvpn

import E "github.com/sagernet/sing/common/exceptions"

var (
	ErrMissingServer               = E.New("missing openvpn server")
	ErrMissingListenAddress        = E.New("missing openvpn listen address")
	ErrUnsupportedProtocol         = E.New("unsupported openvpn protocol")
	ErrUnsupportedMode             = E.New("unsupported openvpn mode")
	ErrHandshakeTimeout            = E.New("openvpn control handshake timeout")
	ErrNoPushReply                 = E.New("openvpn server did not reply to push requests")
	ErrDataChannelNotReady         = E.New("openvpn data channel is not ready")
	ErrClientClosed                = E.New("openvpn client is closed")
	ErrServerClosed                = E.New("openvpn server is closed")
	ErrPeerNotFound                = E.New("openvpn peer not found")
	ErrMissingStaticKey            = E.New("missing openvpn static key")
	ErrCompressionNotSupported     = E.New("openvpn compression is not supported yet")
	ErrOptionNotSupported          = E.New("openvpn option is not supported yet")
	ErrDeprecatedCryptoDisabled    = E.New("openvpn deprecated crypto is disabled")
	ErrAuthenticationFailed        = E.New("openvpn authentication failed")
	ErrServerRestart               = E.New("openvpn server requested restart")
	ErrServerHalt                  = E.New("openvpn server halted session")
	ErrServerExit                  = E.New("openvpn server exited")
	ErrPeerExit                    = E.New("openvpn peer exited")
	ErrPeerRestart                 = E.New("openvpn peer started a new hard-reset session")
	ErrPeerCertificateVerification = E.New("openvpn peer certificate verification failed")
	ErrPeerCertificateRevoked      = E.New("openvpn peer certificate is revoked")
	ErrPeerCertificateExtUsage     = E.New("openvpn peer certificate is missing required extended key usage")
	ErrPeerCertificateKeyUsage     = E.New("openvpn peer certificate is missing required key usage")
	ErrPeerCertificateNSCertType   = E.New("openvpn peer certificate fails ns-cert-type check")
	ErrCRLSignatureInvalid         = E.New("openvpn CRL signature not issued by a trusted CA")
	ErrCRLExpired                  = E.New("openvpn CRL is outside its validity window")
	ErrPullFilterRejected          = E.New("openvpn pushed option rejected by pull-filter")
	ErrCompressionPushRejected     = E.New("openvpn pushed compression rejected by --allow-compression policy")
	ErrCipherNegotiationFailed     = E.New("openvpn cipher negotiation failed with peer")
	ErrRenegotiationRequired       = E.New("openvpn data channel reached renegotiation threshold")
	ErrIPPoolExhausted             = E.New("openvpn server ifconfig pool is exhausted")
	ErrRouteNotFound               = E.New("openvpn route not found")
	ErrInvalidIPPacket             = E.New("invalid ip packet")
	ErrPingRestartTimeout          = E.New("openvpn ping-restart timeout")
	ErrPingExitTimeout             = E.New("openvpn ping-exit timeout")
	ErrNoPendingChallenge          = E.New("no pending openvpn challenge")
	ErrChallengeNotAnswerable      = E.New("openvpn challenge does not accept a response")
	ErrChallengeCanceled           = E.New("openvpn authentication challenge canceled")
	ErrAuthPendingTimeout          = E.New("openvpn pending authentication timed out")
	ErrInactiveTimeout             = E.New("openvpn inactive timeout")
	ErrSessionTimeout              = E.New("openvpn session timeout")
	ErrRemoteAddressExhausted      = E.New("openvpn remote address list exhausted")
	ErrServerResourceLimit         = E.New("openvpn server resource limit reached")
)
