.PHONY: fmt lint lint_install test interop

export GOTOOLCHAIN := local
unexport GOROOT

fmt:
	@golangci-lint fmt

lint:
	GOOS=linux golangci-lint run ./...
	GOOS=android golangci-lint run ./...
	GOOS=windows golangci-lint run ./...
	GOOS=darwin golangci-lint run ./...
#	GOOS=freebsd golangci-lint run ./...

lint_install:
	go install -v github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

test:
	go test ./...
	go -C test test -v -count=1 -timeout 15m ./...

interop:
	OPENVPN_IT=1 go -C test test -race -v -count=1 -timeout 30m $(INTEROP_TEST_FLAGS) ./...
